#!name=kyukurarin
#!desc=aa ka ga mi ne ta chi naiyowa
#!configUrl=https://raw.githubusercontent.com/kiwikurarin/XM93X1CRTABO/refs/heads/main/recognizable.sgmodule
#!howtouse=Shadowrocket
#hi

[General]
bypass-system = true
skip-proxy = *.local, *.crashlytics.com
tun-excluded-routes = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com),(PROTOCOL,UDP)),REJECT

[Header Rewrite]
^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) header-del x-revenuecat-etag
^https?://api.revenuecat.com/.+/(receipts$|subscribers/?(.*?)*$) header-del X-RevenueCat-ETag

[Url Rewrite]
# Chặn quảng cáo Google Video
^https?:\/\/[\w-]+\.googlevideo\.com\/(?!(dclk_video_ads|videoplayback\?)).+&oad _ reject-200

# YouTube Ads
^https?:\/\/(www|s)\.youtube\.com\/api\/stats\/ads _ reject-200
^https?:\/\/(www|s)\.youtube\.com\/(pagead|ptracking) _ reject-200
^https?:\/\/s\.youtube\.com\/api\/stats\/qoe\?adcontext _ reject-200

# General Video Ad request
(^https?:\/\/[\w-]+\.googlevideo\.com\/(?!dclk_video_ads).+?)&ctier=L(&.+?),ctier,(.+) $1$2$3 302

[Script]

#AlightMotion
#hostname = us-central1-alight-creative.cloudfunctions.net
AlightMotion = type=http-response,script-path=https://raw.githubusercontent.com/kiwikurarin/XM93X1CRTABO/refs/heads/main/js/lam.js,pattern=^https:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses,max-size=131072,requires-body=true,timeout=10,enable=true
#************************************#

#LocketGold
#hostname = api.revenuecat.com
revenuecat = type=http-response, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/kiwikurarin/XM93X1CRTABO/refs/heads/main/js/lg.js, requires-body=true, max-size=-1, timeout=60
deleteHeader = type=http-request, pattern=^https:\/\/api\.revenuecat\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/kiwikurarin/XM93X1CRTABO/refs/heads/main/js/ktm.js, timeout=60
#************************************#

#RevenueCatVip
#hostname = api.revenuecat.com
RevenueCatVip = type=http-response, pattern=^https:\/\/api\.(revenuecat|rc-backup)\.com\/.+\/(receipts$|subscribers\/[^/]+$), script-path=https://raw.githubusercontent.com/kiwikurarin/XM93X1CRTABO/refs/heads/main/js/revvingcar.js, requires-body=true, max-size=-1, timeout=60
#RevenueCatDeleteHeader = type=http-request, pattern=^https:\/\/api\.(revenuecat|rc-backup)\.com\/.+\/(receipts|subscribers), script-path=https://raw.githubusercontent.com/kiwikurarin/XM93X1CRTABO/refs/heads/main/js/ktm.js, timeout=60
#************************************#

[Map Local]
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad data-type=text data="" status-code=200
  
[MITM]
hostname = %APPEND%, *.googlevideo.com, youtubei.googleapis.com, www.youtube.com, s.youtube.com, -redirector*.googlevideo.com, api.revenuecat.com, us-central1-alight-creative.cloudfunctions.net
